name: Build and Push to Serv Content

on:
  push:
    branches: [main]

jobs:
  serv_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Push
        uses: nicholasgriffintn/github-branch-deployment-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
          BRANCH: serv_content
          FOLDER: dist
          MESSAGE: 'Build: ({sha}) {msg}'